### ISSUE TITLE
Add-on does not push reviews from upcoming weekend (or dates within 1-2 days of current day)

### ISSUE THREAD

**Issue by timephone** [vasarmilan/AnkiWeekendsAndHolidays#1]
Hey! Love the add-on. However, I'm having trouble getting it to move reviews that are less than a few days in advance of the current date.

For example, if it is a Friday and I command the add-on to reschedule my reviews for all Saturdays and Sundays, it correctly reschedules them away from future weekends but not away from the coming weekend. Even adding the specific dates for the coming weekend does not work. A few cards do get rescheduled, but only a very small amount of the total.

I feel like it may be a problem with the max change days or max change percent, however I do not understand how to fix it (increasing these parameters slightly does not seem to work). I appreciate any assistance you can offer.

**Comment by vasarmilan** [comment]
Hey!

Yes, this is likely because of the "max change percent" setting.

For example, if the interval of a card is less than 5 days and the max change is 20%, that would mean that the interval wouldn't be modified. This is done this way so the intervals of cards just learnt aren't modified, since this could impact the retention more than with mature cards. From what I've seen, this is a reasonable default for most people.

However, if you want to make sure that even cards with short intervals are moved away from the specified day, you can set a higher max_change_percent (eg. 100%). I would advise combining this with a smaller max_days setting, to make sure that cards aren't moved away too much.

I'm closing this now, but please let me know if this does not work for you!
